# =========================================================
# HIRECRAFT AI - APPLICATION CONFIGURATION
# =========================================================

spring.application.name=backend

server.port=8080


# =========================================================
# POSTGRESQL
# =========================================================

spring.datasource.url=jdbc:postgresql://localhost:5432'/hirecraft_ai
spring.datasource.username=postgres
spring.datasource.password=hash0706


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# =========================================================
# FLYWAY
# =========================================================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


# =========================================================
# REDIS
# =========================================================

spring.data.redis.host=localhost
spring.data.redis.port=6379


# =========================================================
# SPRING AI - GOOGLE GEMINI - need to fetch api key from google ai studio
# =========================================================

spring.ai.google.genai.api-key=${GEMINI_API_KEY:[GCP_API_KEY]}
spring.ai.google.genai.chat.model=gemini-2.5-flash


# =========================================================
# FILE UPLOAD
# =========================================================

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# =========================================================
# JWT SECURITY
# =========================================================

spring.security.jwt.secret=UpKa0avipxLIqHAX91d2S3oZUR/Xo0anapiOgzrnuYZxbLtc3dLESnc/wMvDd8BPt6WVg1eBM7rdOX4Y8we8bw==
spring.security.jwt.expiration-ms=86400000


# =========================================================
# LOGGING
# =========================================================

logging.level.com.hirecraft=INFO